apiVersion: v1
kind: Service
metadata:
  name: frontend-dummy
spec:
  type: NodePort
  selector:
    app: frontend-dummy
  ports:
    - protocol: TCP
      port: 5001  
      targetPort: 5001
      nodePort: 30040
