apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-server
spec:
  selector:
    matchLabels:
      app: object-detection-server
  template:
    metadata:
      labels:
        app: object-detection-server
    spec:
      containers:
        - name: object-detection-server
          image: mohanabathula/detection_pod:v1
          ports:
            - containerPort: 5002