apiVersion: v1
kind: Service
metadata:
  name: object-detection-server
spec:
  type: NodePort
  selector:
    app: object-detection-server
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30055
